/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.EmpresaController;
import modelo.tablas.AgenciaTabla;
import modelo.tablas.DetalleTabla;

/**
 *
 * @author jona
 */
public class Frm_Empresas extends javax.swing.JDialog {

    private EmpresaController ac = new EmpresaController();
    private EmpresaController resul = new EmpresaController();
    private AgenciaTabla at = new AgenciaTabla();
    private DetalleTabla dt = new DetalleTabla();
    private String cabecera[];

    /**
     * Creates new form Frm_Empresas
     */
    public Frm_Empresas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTabla();
        cargarTabla2();
        
    }
//
//    public void cargarcabecera() {
//        this.cabecera = new String[cbxmes.getModel().getSize()];
//        for (int i = 0; i < cbxmes.getModel().getSize(); i++) {
//            this.cabecera[i] = cbxmes.getModel().getElementAt(i);
//        }
//    }

    public void cargarTabla() {
        //at.setCabecera(cabecera);
        try {
            at.setDato(ac.getVentas());
            tbl_meses.setModel(at);
            tbl_meses.updateUI();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public Double[][] cargarmatriz(){
        Double matriz[][] = {{0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0}};
        Double prome[] = ac.promedio(ac.getVentas());
        Double total[] = ac.calcular(ac.getVentas());
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 5; j++) {
                if(i==0){
                matriz[0][j]=total[j];
                }else if(i==1){
                matriz[1][j]=prome[j];
                }
            }
        }
        return matriz;
    
    }
     public void cargarTabla2() {
        //at.setCabecera(cabecera);
        try {
            Double deta[][] = cargarmatriz();
            dt.setDato(deta);
            tbl_detalles.setModel(dt);
            tbl_detalles.updateUI();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void limpiar(){
        txtvalor.setText("");
        cbxAgencia.setSelectedIndex(0);
        cbxmes.setSelectedIndex(0);
    }

    private void ingresar() {
        Double valor = Double.parseDouble(txtvalor.getText());
        int mes = cbxmes.getSelectedIndex();
        int agencia = cbxAgencia.getSelectedIndex();
        ac.ingresar(agencia, mes, valor);
        cargarTabla();
        limpiar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cbxAgencia = new javax.swing.JComboBox<>();
        bntingresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxmes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_meses = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_detalles = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empresa"));
        jPanel2.setLayout(null);

        cbxAgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agencia 1", "Agencia 2", "Agencia 3", "Agencia 4", "Agencia 5" }));
        cbxAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAgenciaActionPerformed(evt);
            }
        });
        jPanel2.add(cbxAgencia);
        cbxAgencia.setBounds(120, 30, 150, 23);

        bntingresar.setText("Ingresar");
        bntingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntingresarActionPerformed(evt);
            }
        });
        jPanel2.add(bntingresar);
        bntingresar.setBounds(330, 70, 90, 23);

        jLabel2.setText("Agencia: ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 30, 80, 20);

        jLabel3.setText("Mes :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(300, 30, 50, 20);

        cbxmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmesActionPerformed(evt);
            }
        });
        jPanel2.add(cbxmes);
        cbxmes.setBounds(360, 30, 150, 23);

        jLabel1.setText("Ventas: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 70, 70, 17);
        jPanel2.add(txtvalor);
        txtvalor.setBounds(120, 70, 150, 23);

        jButton1.setText("Detalles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(430, 70, 82, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 590, 120);

        tbl_meses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_meses);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 590, 180);

        tbl_detalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_detalles);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(150, 340, 452, 100);

        jLabel4.setText("Total:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 360, 60, 17);

        jLabel5.setText("Promedio:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 380, 70, 17);

        setSize(new java.awt.Dimension(622, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntingresarActionPerformed
        // TODO add your handling code here:
        ingresar();

    }//GEN-LAST:event_bntingresarActionPerformed

    private void cbxmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxmesActionPerformed

    private void cbxAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAgenciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cargarTabla2();
       ac.vesmenorventasagencias(ac.getVentas());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Empresas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Empresas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Empresas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Empresas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Empresas dialog = new Frm_Empresas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntingresar;
    private javax.swing.JComboBox<String> cbxAgencia;
    private javax.swing.JComboBox<String> cbxmes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_detalles;
    private javax.swing.JTable tbl_meses;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
